intershop/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import GoodsViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register('goods', GoodsViewSet, basename='goods')
#router.register(r'goods/(?P<group_id>\d+)/',GoodsViewSet, basename='goods')

urlpatterns = [
    path('v1/', include(router.urls)),
]

intershop/goods/urls.py
from django.urls import include, path

from . import views

app_name = 'goods'

urlpatterns = [
    path('', views.index, name='index'),
    path('busket/', views.busket, name='busket'),
    path('goods/<int:goods_id>/add/',views.goods_add_to_busket, name='add'),
    path('goods/<int:goods_id>/delete/',views.goods_delete_from_busket, name='delete'),
    path('order/<int:order_id>/apply/', views.order_apply, name='order_apply'),
]

intershop/intershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django_otp.admin import OTPAdminSite
  
admin.site.__class__ = OTPAdminSite
admin.site.site_header = 'Интернет-магазин Альбранта Е.О.'
admin.site.index_title = 'Админка'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),    
    path('', include('goods.urls', namespace='goods')),
    path('api/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

intershop/goods/models.py
import datetime

from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Название',
        help_text='Выберите группу')
    slug = models.SlugField(max_length=20, unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        ordering = ['title']
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'    

    def __str__(self):
        return self.title

# слово goods означает как товар, так и товары
class Goods(models.Model):
    article = models.CharField(
        max_length=20,
        verbose_name='Артикль',
        help_text='Введите артикль товара'        
    )
    caption = models.CharField(
        max_length=30,
        verbose_name='Название товара',
        help_text='Введите название товара'         
    )
    group = models.ManyToManyField(Group)
    quantity = models.IntegerField(default=1)
    # в идеале нужно выносить количество товара в отдельную структуру
    # рассчитывая приход на склад, продажу со склада,
    # для данного проекта это упростим - будет просто количество товара
    price = models.FloatField(default=100)
    
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
    
    def __str__(self):
        return self.caption[:20]


class Order(models.Model):
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="orders")
    is_done = models.BooleanField(
        default=False,
        verbose_name='Выполнен'
    )
    order_date = models.DateTimeField(
        'Дата заказа',
        auto_now_add=True
    )
    
    def __str__(self):
        return f'Заказ № {self.id} от {self.order_date}'


# связь "многие-ко-многим" здесь не получится использовать, т.к. 
# для каждого товара нужно указывать его количество в заказах
class GoodsInOrder(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name='goods_in_order'
    )
    goods = models.ForeignKey(
        Goods, on_delete=models.CASCADE, related_name='goods_in_order'
    )
    quantity = models.IntegerField(default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['order', 'goods'],
                name='unique_order_goods'
            )
        ]

    def __str__(self):
        return self.goods.caption

intershop/goods/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from intershop.settings import GOODS_PER_PAGE

from .models import Goods, Order, User, GoodsInOrder


def index(request):
    goods_list = Goods.objects.all()
    paginator = Paginator(goods_list, GOODS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'index': True
    }
    return render(request, 'goods/index.html', context)


def busket(request):
    customer = get_object_or_404(User, username=request.user.username)
    current_order, created = Order.objects.get_or_create(customer=customer, is_done=False)
    goods_in_busket_list = current_order.goods_in_order.all()
    goods_in_busket_count = current_order.goods_in_order.count()
    paginator = Paginator(goods_in_busket_list, GOODS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'count': goods_in_busket_count,
        'index': True,
        'order': current_order.id
    }
    return render(request, 'goods/busket.html', context)


@login_required
def order_apply(request, order_id):
    current_order = get_object_or_404(Order, id=order_id)
    current_order.is_done = True
    current_order.order_date = datetime.datetime.now()
    current_order.save()
    goods_in_busket_list = current_order.goods_in_order.all()
    goods_in_busket_count = current_order.goods_in_order.count()
    paginator = Paginator(goods_in_busket_list, GOODS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'count': goods_in_busket_count,
        'index': True,
        'order': order_id
    }
    return render(request, 'goods/apply.html', context)


@login_required
def goods_add_to_busket(request, goods_id):
    goods = get_object_or_404(Goods, id=goods_id)
    order, created = Order.objects.get_or_create(is_done=False, customer=request.user)
    if not GoodsInOrder.objects.filter(order=order, goods=goods).exists():
        GoodsInOrder.objects.create(order=order, goods=goods)
    else:
        goodsinorder_object = GoodsInOrder.objects.get(order=order, goods=goods)
        goodsinorder_object.quantity += 1
        goodsinorder_object.save()
    return redirect('goods:index')

@login_required
def goods_delete_from_busket(request, goods_id):
    goods = get_object_or_404(GoodsInOrder, id=goods_id)
    goods.delete()
    return redirect('goods:busket')

intershop/templates/goods/apply.html
{% extends 'base.html' %}
{% block title %} Заказ оплачен{% endblock %}
{% block header %}Заказ оплачен{% endblock %}
{% block content %}
    <div class="container py-5">     
      <h1>Заказ успешно оплачен </h1> 
      <h3>(всего: {{count}})</h3>
      
      {% for elem in page_obj %}

      <p><b>{{ elem.goods.caption }}</b></p>

        <p> Кол-во: {{ elem.quantity }} шт </p>
        <p> Цена: {{ elem.goods.price}} рублей </p>
     
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'goods/includes/paginator.html' %}
    </div>
{% endblock %} 

intershop/templates/goods/busket.html
{% extends 'base.html' %}
{% block title %} Все товары в корзине{% endblock %}
{% block header %}Все товары в корзине{% endblock %}
{% block content %}
    <div class="container py-5">     
      <h1>Товары в корзине (всего: {{count}})</h1>
      {% if count %}
      <p> <a
        class="btn btn-lg btn-primary"
        href="{% url 'goods:order_apply' order %}" role="button"
      >
        Оплатить заказ</a></p>
      {% endif %}
      
      {% for elem in page_obj %}

      <p><b>{{ elem.goods.caption }}</b></p>
        <ul>
          {% if elem.goods.group %}
          {% for gr in elem.goods.group.all %}
            <li>
              Группа: {{ gr.title }}
            </li>
            {%endfor%}
          {% endif %}
        </ul>

        <p> Кол-во: {{ elem.quantity }} шт </p>
        <p> Цена: {{ elem.goods.price}} рублей </p>
        <p>
          <a
            class="btn btn-lg btn-light"
            href="{% url 'goods:delete' elem.id %}" role="button"
          >
            Убрать из козины</a>
        </p>       
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'goods/includes/paginator.html' %}
    </div>
{% endblock %} 

intershop/templates/goods/index.html
{% extends 'base.html' %}
{% block title %} Все товары на сайте{% endblock %}
{% block header %}Все товары на сайте{% endblock %}
{% block content %}
    <div class="container py-5">     
      <h1>Все товары на сайте</h1>
      
      {% for goods in page_obj %}
      <p><b>{{ goods.caption }}</b></p>      
        <ul>
          {% if goods.group %}
          {% for gr in goods.group.all %}
            <li>
              Группа: {{ gr.title }}
            </li>
            {%endfor%}
          {% endif %}
        </ul>       

        <p> Всего на складе: {{ goods.quantity }} шт </p>
        <p> Цена: {{ goods.price}} рублей </p>
        <p>
        {% if in_busket %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'goods:delete' goods.id %}" role="button"
        >
          Убрать из козины
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'goods:add' goods.id %}" role="button"
          >
            Добавить в корзину
          </a>
       {% endif %}
      </p>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'goods/includes/paginator.html' %}
    </div>
{% endblock %} 