intershop/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import GoodsViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register('goods', GoodsViewSet, basename='goods')
#router.register(r'goods/(?P<group_id>\d+)/',GoodsViewSet, basename='goods')

urlpatterns = [
    path('v1/', include(router.urls)),
]

intershop/goods/urls.py
from django.urls import include, path

from . import views

app_name = 'goods'

urlpatterns = [
    path('', views.index, name='index'),
    path('busket/', views.busket, name='busket'),
    path('goods/<int:goods_id>/add/',views.goods_add_to_busket, name='add'),
    path('goods/<int:goods_id>/delete/',views.goods_delete_from_busket, name='delete'),
    path('order/<int:order_id>/apply/', views.order_apply, name='order_apply'),
]

intershop/intershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django_otp.admin import OTPAdminSite
  
admin.site.__class__ = OTPAdminSite
admin.site.site_header = 'Интернет-магазин Альбранта Е.О.'
admin.site.index_title = 'Админка'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),    
    path('', include('goods.urls', namespace='goods')),
    path('api/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

intershop/templates/includes/footer.html
<p class="m-0 text-dark text-center ">© {{ year }} Copyright Альбрант Евгений, 2022</p>

intershop/templates/includes/header.html
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'goods:index' %}">
        {% load static %}
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:green">Inter</span>shop
      </a>

      {% with request.resolver_match.view_name as view_name %} 

      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'goods:index' %}active{% endif %}" href="{% url 'goods:index' %}">Товары</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'goods:busket' %}active{% endif %}" href="{% url 'goods:busket' %}">Корзина</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}" href="{% url 'password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'logout' %}">Выйти</a>
        </li>
        <li class="nav-link">
           <b>Пользователь: {{ user.username }} </b>
        </li>
        {% else %}

        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
      </ul>
      {% endif %}
      {% endwith %}
    </div>
  </nav>      